[supervisord]
nodaemon=true

[program:rust_api]
command=/usr/src/app/mi-proyecto-enpoint
autostart=true
autorestart=true

[program:flask_frontend]
command=python3 /usr/src/app/frontend_flask.py
autostart=true
autorestart=true
